server:
  port: 3030
spring:
  security:
    user:
      name: furkan
      password: 123
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/UberAuthDB
    username: postgres
    password: asd123asd
  jpa:
    hibernate:
      ddl-auto: update

TokenKey: "ThWmZq4t7w!z%C*F-JaNdRgUjXn2r5u8x/A?D(G+KbPeShVmYp3s6v9y$B&E)H@M"

rabbitmq:
  exchange:
    direct: "direct_exchange"
  queue:
    register-driver: "queue_register_driver"
    register-passenger: "queue_register_passenger"
  key:
    register-driver: "key_register_driver"
    register-passenger: "key_register_passenger"