server:
  port: 7071
spring:
  security:
    user:
      name: furkan
      password: 123
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: driver-service
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5500/DriverDB
    username: postgres
    password: asd123asd
  jpa:
    hibernate:
      ddl-auto: update